//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCradle.FacadeServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FacadeServiceReference.IFacadeRestServiceImpl")]
    public interface IFacadeRestServiceImpl {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacadeRestServiceImpl/XmlData", ReplyAction="http://tempuri.org/IFacadeRestServiceImpl/XmlDataResponse")]
        string XmlData(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacadeRestServiceImpl/JsonDataPost", ReplyAction="http://tempuri.org/IFacadeRestServiceImpl/JsonDataPostResponse")]
        string JsonDataPost();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFacadeRestServiceImplChannel : TestCradle.FacadeServiceReference.IFacadeRestServiceImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FacadeRestServiceImplClient : System.ServiceModel.ClientBase<TestCradle.FacadeServiceReference.IFacadeRestServiceImpl>, TestCradle.FacadeServiceReference.IFacadeRestServiceImpl {
        
        public FacadeRestServiceImplClient() {
        }
        
        public FacadeRestServiceImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FacadeRestServiceImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacadeRestServiceImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacadeRestServiceImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string XmlData(string id) {
            return base.Channel.XmlData(id);
        }
        
        public string JsonDataPost() {
            return base.Channel.JsonDataPost();
        }
    }
}
